# Example haste setup.
#
# It measures a couple of shells using a simple benchmark.

proc_execs = 3
inproc_iters = 5

[executors]
bash = "bash"
zsh = "zsh"

[suites.example]
dir = "."
harness = "./outer_harness.sh"

[suites.example.benchmarks.bigloop]
extra_args = ["10000"]
